FROM ruby:3.3.0

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  default-libmysqlclient-dev \
  default-mysql-client \
  nodejs \
  yarn \
  git \
  vim \
  curl \
  && rm -rf /var/lib/apt/lists/*

RUN gem install bundler:2.6.9

WORKDIR /app

CMD ["irb"]
